package com.courses.internshipapp.modules.internship.enums

enum class Major {
    SOFTWARE_ENGINEERING,
    ARTIFICIAL_INTELLIGENCE,
    DATA_SCIENCE,
    COMPUTER_SCIENCE,
    CYBERSECURITY,
    VIDEO_GAMES,
    IOT,
    INFORMATION_SYSTEMS,
    NETWORKS_AND_TELECOMMUNICATIONS,
    CLOUD_COMPUTING,
    EMBEDDED_SYSTEMS,
    HUMAN_COMPUTER_INTERACTION,
    MACHINE_LEARNING,
    BUSINESS_INTELLIGENCE,
    DEVOPS,
    MOBILE_DEVELOPMENT,
    WEB_DEVELOPMENT
}
